### ISSUE TITLE
Extra whitespace in DhParam initializers causes the script runner to crash

### ISSUE THREAD

**Issue by HotelCalifornia** [CommonWealthRobotics/BowlerBuilder#52]
**Describe the bug**
See title and attached stacktrace.

**Steps To Reproduce**
The following code produces the issue:
```kt
    private val epsonC3 = immutableListOf(
        DhParam(320,    0, 100,  90), // 1
        DhParam(0,    180,   0, -90), // 2
        DhParam(400,  180,   0,  90), // 3
        DhParam(0,   -090,   0, -90), // 4
        DhParam(350,  180,   0,  90), // 5
        DhParam(0,    180,   0, -90), // 6
        DhParam(65,     0,   0,   0), // endeffector
    )
```
produces the following stacktrace:
<details>
<summary>stacktrace</summary>
<pre>
WARNING: Exception running script:
de.swirtz.ktsrunner.objectloader.LoadException: Cannot load script
        at com.neuronrobotics.bowlerkernel.scripting.DefaultScript$handleKotlin$$inlined$invoke$lambda$1.invokeSuspend(DefaultScript.kt:174)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:235)
        at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:81)
        at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:123)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:45)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.neuronrobotics.bowlerkernel.scripting.DefaultScript.runScript(DefaultScript.kt:71)
        at com.neuronrobotics.bowlerbuilder.controller.scripteditor.ScriptRunnerUtilKt.runAndHandleScript(ScriptRunnerUtil.kt:49)
        at com.neuronrobotics.bowlerbuilder.controller.scripteditor.TextScriptRunner.runScript(TextScriptRunner.kt:63)
        at com.neuronrobotics.bowlerbuilder.controller.scripteditor.TextScriptRunner.runScript$default(TextScriptRunner.kt:50)
        at com.neuronrobotics.bowlerbuilder.view.scripteditor.AceEditorView$root$1$2$1.invoke(AceEditorView.kt:88)
        at com.neuronrobotics.bowlerbuilder.view.scripteditor.AceEditorView$root$1$2$1.invoke(AceEditorView.kt:51)
        at com.neuronrobotics.bowlerbuilder.view.util.ThreadMonitoringButton$2$1.invoke(ThreadMonitoringButton.kt:45)
        at com.neuronrobotics.bowlerbuilder.view.util.ThreadMonitoringButton$2$1.invoke(ThreadMonitoringButton.kt:31)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: javax.script.ScriptException: error: expecting ')'
        DhParam(0,   -090,   0, -90), // 4
                       ^
error: property getter or setter expected
        DhParam(0,   -090,   0, -90), // 4
                                    ^
error: expecting member declaration
        DhParam(350,  180,   0,  90), // 5
        ^
error: expecting member declaration
        DhParam(350,  180,   0,  90), // 5
               ^
error: expecting member declaration
        DhParam(350,  180,   0,  90), // 5
                ^
error: expecting member declaration
        DhParam(350,  180,   0,  90), // 5
                   ^
error: expecting member declaration
        DhParam(350,  180,   0,  90), // 5
                      ^
error: expecting member declaration
        DhParam(350,  180,   0,  90), // 5
                         ^
error: expecting member declaration
        DhParam(350,  180,   0,  90), // 5
                             ^
error: expecting member declaration
        DhParam(350,  180,   0,  90), // 5
                              ^
error: expecting member declaration
        DhParam(350,  180,   0,  90), // 5
                                 ^
error: expecting member declaration
        DhParam(350,  180,   0,  90), // 5
                                   ^
error: expecting member declaration
        DhParam(350,  180,   0,  90), // 5
                                    ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
        ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
               ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
                ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
                 ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
                      ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
                         ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
                             ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
                              ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
                                ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
                                 ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
                                   ^
error: expecting member declaration
        DhParam(0,    180,   0, -90), // 6
                                    ^
error: expecting member declaration
        DhParam(65,     0,   0,   0), // endeffector
        ^
error: expecting member declaration
        DhParam(65,     0,   0,   0), // endeffector
               ^
error: expecting member declaration
        DhParam(65,     0,   0,   0), // endeffector
                ^
error: expecting member declaration
        DhParam(65,     0,   0,   0), // endeffector
                  ^
error: expecting member declaration
        DhParam(65,     0,   0,   0), // endeffector
                        ^
error: expecting member declaration
        DhParam(65,     0,   0,   0), // endeffector
                         ^
error: expecting member declaration
        DhParam(65,     0,   0,   0), // endeffector
                             ^
error: expecting member declaration
        DhParam(65,     0,   0,   0), // endeffector
                              ^
error: expecting member declaration
        DhParam(65,     0,   0,   0), // endeffector
                                  ^
error: expecting member declaration
        DhParam(65,     0,   0,   0), // endeffector
                                   ^
error: expecting member declaration
        DhParam(65,     0,   0,   0), // endeffector
                                    ^
error: expecting member declaration
    )
    ^

        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:65)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
        at javax.script.AbstractScriptEngine.eval(Unknown Source)
        at com.neuronrobotics.bowlerkernel.scripting.DefaultScript$handleKotlin$$inlined$invoke$lambda$1.invokeSuspend(DefaultScript.kt:170)
        ... 18 more
</pre>
</details>

**Expected behavior**
The script runner should not crash, unless I'm missing something about Kotlin)

**Version**
0.2.0 (beta 3)

**Comment by Octogonapus** [comment]
It seems the problem is `-090`. This is a Kotlin issue. Changing it to `-90` seems to work. Also, you have an extra comma at the end of the list.

**Comment by HotelCalifornia** [comment]
Ah, knew I was missing something. Thanks
