### ISSUE TITLE
Cannot submit an issue report from the UI

### ISSUE THREAD

**Issue by HotelCalifornia** [CommonWealthRobotics/BowlerBuilder#53]
**Describe the bug**
When clicking the submit button in the issue report dialog, nothing happens (except for a stacktrace)

**Steps To Reproduce**
1. Open issue report dialog
2. Fill in the fields
3. Click submit

It seems that the following trace occurs regardless of which logfile options are selected:

```
Apr 08, 2019 3:16:45 PM com.neuronrobotics.bowlerbuilder.BowlerBuilder$2 uncaughtException
SEVERE: java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(Unknown Source)
        at com.neuronrobotics.bowlerbuilder.controller.util.LoggerUtilities$Companion.getApplicationVersion(LoggerUtilities.kt:134)
        at com.neuronrobotics.bowlerbuilder.controller.ReportIssueController.getIssueBodyFooter(ReportIssueController.kt:102)
        at com.neuronrobotics.bowlerbuilder.controller.ReportIssueController.reportIssue$KotlinUI(ReportIssueController.kt:56)
        at com.neuronrobotics.bowlerbuilder.view.ReportIssueView$root$1$1$5$1$1$1.invoke(ReportIssueView.kt:94)
        at com.neuronrobotics.bowlerbuilder.view.ReportIssueView$root$1$1$5$1$1$1.invoke(ReportIssueView.kt:26)
        at tornadofx.FXTask.call(Async.kt:459)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Expected behavior**
Should be able to submit an issue through the UI successfully

**Version**
0.2.0 (beta 3)

**Comment by Octogonapus** [comment]
@HotelCalifornia When you get back in the lab tomorrow please put the "Cannot load virtual filesystem for Windows" stack trace in a comment here.

**Comment by HotelCalifornia** [comment]
```
Apr 08, 2019 12:16:10 PM com.neuronrobotics.bowlerbuilder.controller.gitmenu.LoginManager loginToken
INFO: Logged in.
WARN: Failed to initialize native filesystem for Windows
java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.
	at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:90)
	at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:68)
	at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.findBinFile(PathManager.java:169)
	at org.jetbrains.kotlin.com.intellij.util.lang.UrlClassLoader.loadPlatformLibrary(UrlClassLoader.java:321)
	at org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:48)
	at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:62)
	at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:54)
	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.setFileAttributes(ZipHandler.java:61)
	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:43)
	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:39)
	at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache.java:60)
	at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:52)
	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.getCachedZipFileHandle(ZipHandler.java:83)
	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.acquireZipHandle(ZipHandler.java:129)
	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandlerBase.createEntriesMap(ZipHandlerBase.java:44)
	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHandler.java:197)
	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandler.java:42)
	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.lambda$new$0(CoreJarFileSystem.java:33)
	at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap$3.create(ConcurrentFactoryMap.java:212)
	at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:59)
	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(CoreJarFileSystem.java:44)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRoot(KotlinCoreEnvironment.kt:412)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRootToVirtualFile(KotlinCoreEnvironment.kt:391)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.access$contentRootToVirtualFile(KotlinCoreEnvironment.kt:121)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$6.invoke(KotlinCoreEnvironment.kt:269)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$6.invoke(KotlinCoreEnvironment.kt:121)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:70)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:276)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:121)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:513)
	at org.jetbrains.kotlin.cli.jvm.repl.GenericReplChecker.<init>(GenericReplChecker.kt:62)
	at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:57)
	at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:55)
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:45)
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplCompiler(KotlinJsr223JvmLocalScriptEngine.kt)
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:51)
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getLocalEvaluator(KotlinJsr223JvmLocalScriptEngine.kt)
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplEvaluator(KotlinJsr223JvmLocalScriptEngine.kt:53)
	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.createState(KotlinJsr223JvmLocalScriptEngine.kt:57)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.createState$default(KotlinJsr223JvmScriptEngineBase.kt:46)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.getCurrentState(KotlinJsr223JvmScriptEngineBase.kt:53)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.nextCodeLine(KotlinJsr223JvmScriptEngineBase.kt:44)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:59)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
	at javax.script.AbstractScriptEngine.eval(Unknown Source)
	at com.neuronrobotics.bowlerkernel.scripting.DefaultScript$handleKotlin$$inlined$invoke$lambda$1.invokeSuspend(DefaultScript.kt:170)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:235)
	at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:81)
	at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:123)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:45)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.neuronrobotics.bowlerkernel.scripting.DefaultScript.runScript(DefaultScript.kt:71)
	at com.neuronrobotics.bowlerbuilder.controller.scripteditor.ScriptRunnerUtilKt.runAndHandleScript(ScriptRunnerUtil.kt:49)
	at com.neuronrobotics.bowlerbuilder.controller.scripteditor.TextScriptRunner.runScript(TextScriptRunner.kt:63)
	at com.neuronrobotics.bowlerbuilder.controller.scripteditor.TextScriptRunner.runScript$default(TextScriptRunner.kt:50)
	at com.neuronrobotics.bowlerbuilder.view.scripteditor.AceEditorView$root$1$2$1.invoke(AceEditorView.kt:88)
	at com.neuronrobotics.bowlerbuilder.view.scripteditor.AceEditorView$root$1$2$1.invoke(AceEditorView.kt:51)
	at com.neuronrobotics.bowlerbuilder.view.util.ThreadMonitoringButton$2$1.invoke(ThreadMonitoringButton.kt:45)
	at com.neuronrobotics.bowlerbuilder.view.util.ThreadMonitoringButton$2$1.invoke(ThreadMonitoringButton.kt:31)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by Octogonapus** [comment]
Fix: https://github.com/arturbosch/detekt/pull/634
`System.setProperty("idea.io.use.fallback", "true")`
